name: Merged Mining Proxy CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Set GOPATH
      run: |
        mkdir -p $HOME/go
        echo "export GOPATH=$HOME/go" >> $GITHUB_ENV

    - name: Initialize Go module if not present
      run: |
        if [ ! -f go.mod ]; then
          go mod init github.com/BlackPeter13/proxy/mergedMiningProxy
          go mod tidy
        fi
      working-directory: mergedMiningProxy

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod tidy
      working-directory: mergedMiningProxy

    - name: Run tests
      run: go test ./...
      working-directory: mergedMiningProxy
